# Generated by Django 3.2.13 on 2022-05-04 23:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_label', models.IntegerField(null=True)),
                ('vehicle_current_status', models.IntegerField(default=1)),
                ('position_latitude', models.DecimalField(decimal_places=7, max_digits=10, null=True)),
                ('position_longitude', models.DecimalField(decimal_places=8, max_digits=10, null=True)),
                ('geographic_point', models.CharField(max_length=100)),
                ('position_speed', models.IntegerField(default=0)),
                ('position_odometer', models.IntegerField(default=0)),
                ('trip_id', models.BigIntegerField(null=True)),
                ('trip_schedule_relationship', models.IntegerField(choices=[(0, 'No'), (2, 'Yes')])),
                ('trip_route', models.IntegerField(null=True)),
                ('trip_start_date', models.IntegerField(null=True)),
                ('date_creation', models.DateTimeField(auto_now=True)),
                ('date_updated', models.DateTimeField(auto_now_add=True)),
                ('town_hall', models.CharField(max_length=50)),
            ],
        ),
    ]
